title: Ruby & Ruby on Rails books, courses and more
description: The largest collection of books, courses, podcasts, newsletters about Ruby and Ruby On Rails


collections:
  books_ruby:
    output: true
    permalink: /ruby/book/:name
  books_rails:
    output: true
    permalink: /ruby-on-rails/book/:name

defaults:
  -
    scope:
      path: ""
      type: "books_ruby"
    values:
      layout: "book"
      root_page: "ruby/books.html"
  -
    scope:
      path: ""
      type: "books_rails"
    values:
      layout: "book"
      root_page: "rails/books.html"

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
