title: Ruby & Ruby on Rails books, courses and more
description: The largest collection of books, courses, podcasts, newsletters about Ruby and Ruby On Rails
url: rubyandrails.info
social:
  name: Leonid Nazarov
  links:
    - https://twitter.com/nleonid
logo: /assets/og_cover.png

collections:
  books_ruby:
    output: true
    permalink: /ruby/book/:name:output_ext
  books_rails:
    output: true
    permalink: /ruby-on-rails/book/:name:output_ext

defaults:
  - scope:
      path: "assets/images/books/ruby"
    values:
      image: true
  -
    scope:
      path: ""
      type: "books_ruby"
    values:
      layout: "book"
      root_page: "ruby/books.html"
  -
    scope:
      path: ""
      type: "books_rails"
    values:
      layout: "book"
      root_page: "ruby-on-rails/books.html"

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - gulpfile.babel.js
  - LICENSE.md
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - src
  - tailwind.config.js
  - netlify.toml
